services:
  app:
    image: ghcr.io/shba007/portfolio-shirsendu:latest@sha256:1b0aaf33cf0d832111722f73cd17f06015f65c181d3e55dcfa0c806210356cf4
    env_file:
      - .env
    volumes:
      - portfolio-shirsendu_static:/app/static
      - portfolio-shirsendu_data:/app/.data
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  portfolio-shirsendu_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/portfolio-shirsendu/static
  portfolio-shirsendu_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/portfolio-shirsendu/.data

networks:
  internal:
    driver: overlay
